/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GenericError {
  message?: string;
}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Create an item in the store
 */
export interface CreateItem {
  name: string;
  description?: string;
  price?: number;
  quantity?: number;
}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An item in the store
 */
export interface Item {
  id?: string;
  name?: string;
  description?: string;
  price?: number;
  quantity?: number;
  createdAt?: string;
  updatedAt?: string;
}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ListItems = {
  id?: string;
  name?: string;
  description?: string;
  price?: number;
  quantity?: number;
  createdAt?: string;
  updatedAt?: string;
  [k: string]: unknown;
}[];
